spring.config.import=optional:file:.env[.properties]

# 1. THÔNG TIN KẾT NỐI DATABASE (Neon PostgreSQL) - Lấy từ file .env
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. CẤU HÌNH HIBERNATE (Tự động tạo/cập nhật bảng)
spring.jpa.hibernate.ddl-auto=create

# 3. HIỂN THỊ CÂU LỆNH SQL TRÊN TERMINAL (Để dễ debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. CHỌN CỔNG CHẠY SERVER (Tùy chọn)
# Lấy từ file env, nếu trong env không có thì mặc định là 8081
server.port=${SERVER_PORT:8081}

# 5. CẤU HÌNH GIỚI HẠN UPLOAD FILE (Khắc phục lỗi HTTP ERROR 413)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB